import {
  AlertTriangle,
  Activity,
  ArrowDownToLine,
  ArrowUpToLine,
  ArrowUpRight,
  BarChart3,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Coins,
  Compass,
  Copy,
  Landmark,
  Gauge,
  Layers,
  Lock,
  Radar,
  RefreshCcw,
  Settings,
  Sparkles,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const cabIconRegistry = {
  radar: Radar,
  wallet: Wallet,
  warning: AlertTriangle,
  info: CircleHelp,
  dashboard: Gauge,
  pools: Layers,
  deposits: Wallet,
  strategies: Sparkles,
  activity: Activity,
  rewards: BarChart3,
  governance: Landmark,
  navigation: Compass,
  settings: Settings,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  externalLink: ArrowUpRight,
  arrowDownToLine: ArrowDownToLine,
  arrowUpToLine: ArrowUpToLine,
  coins: Coins,
  copy: Copy,
  lock: Lock,
  refreshCcw: RefreshCcw,
} as const satisfies Record<string, LucideIcon>;

export type CabIconName = keyof typeof cabIconRegistry;
