import { cabColors } from "@/design-system/tokens/colors";

/** Single source of truth for Tamagui color tokens — derived from cabColors. */
export const tamaguiColorTokens = {
  background: cabColors.brand.cabNight,
  deepSpace: cabColors.brand.deepSpace,
  controlBlue: cabColors.brand.controlBlue,
  surface: cabColors.surface.darkSurface,
  surfaceElevated: cabColors.surface.elevatedSurface,
  border: cabColors.surface.border,
  foreground: cabColors.text.primary,
  secondary: cabColors.text.secondary,
  muted: cabColors.text.muted,
  accent: cabColors.brand.signalTeal,
  signalTealUi: cabColors.brandExtended.signalTealUi,
  signalTealMuted: cabColors.brandExtended.signalTealMuted,
  signalTealGlow: cabColors.brandExtended.signalTealGlow,
  electricBlue: cabColors.brand.electricBlue,
  gold: cabColors.brand.cabGold,
  primaryActionBg: cabColors.action.primaryBg,
  primaryActionText: cabColors.action.primaryText,
  primaryActionBorder: cabColors.action.primaryBorder,
  primaryActionHoverBg: cabColors.action.primaryHoverBg,
  secondaryActionBg: cabColors.action.secondaryBg,
  secondaryActionText: cabColors.action.secondaryText,
  secondaryActionBorder: cabColors.action.secondaryBorder,
  secondaryActionHoverBorder: cabColors.action.secondaryHoverBorder,
  technicalActionText: cabColors.action.technicalText,
  technicalActionBorder: cabColors.action.technicalBorder,
  technicalActionHoverBorder: cabColors.action.technicalHoverBorder,
  technicalActionGlow: cabColors.action.technicalGlow,
  success: cabColors.semantic.success,
  warning: cabColors.semantic.warning,
  danger: cabColors.semantic.danger,
  info: cabColors.semantic.info,
} as const;
